logging:
  level:
    root: DEBUG
  file:
    path: log
server:
  port: 9003
spring:
  jackson:
    generator:
      write-numbers-as-strings: true
  application:
    name: jxyz
  rabbitmq:
    host: 47.57.108.128
    port: 5672
    username: admin
    password: mypassword
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-8vbif49m6k7l651e5fo.mysql.zhangbei.rds.aliyuncs.com:3306/jxyz?serverTimezone=UTC&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: Liqin1988
    hikari:
      connection-timeout: 15000
      auto-commit: true
      max-lifetime: 600000
      pool-name: DatebookHikariCP
      minimum-idle: 5
      connection-test-query: SELECT 1
      idle-timeout: 30000
      maximum-pool-size: 15
      
jxyz:
  created_user: 王小贱
  minio_data_base_path: /opt/minio/data
  upzip_base_path: /home/unzip
